# Generated by Django 3.1.7 on 2021-03-31 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_auto_20210331_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 13, 3, 53, 489346)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 13, 3, 53, 489346)),
        ),
    ]
