# Generated by Django 3.1.7 on 2021-04-01 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_auto_20210401_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_target',
            field=models.PositiveBigIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
