# Generated by Django 3.1.7 on 2021-04-01 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0013_project_total_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.PositiveBigIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
