# Generated by Django 3.1.7 on 2021-04-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0014_auto_20210401_1726'),
        ('funds', '0013_donation_date'),
    ]

    operations = [
    ]
