# Generated by Django 3.1.7 on 2021-03-31 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_auto_20210331_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 11, 6, 1, 890578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 11, 6, 1, 890578, tzinfo=utc)),
        ),
    ]
