# Generated by Django 3.1.7 on 2021-04-01 07:36

from django.db import migrations, models
import django.db.models.deletion
import funds.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_auto_20210331_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=funds.models.project.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='funds.category'),
        ),
    ]
