# Generated by Django 3.1.7 on 2021-04-01 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_auto_20210401_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
